---
- name: Inicialização do master Kubernetes
  hosts: master
  become: yes

  tasks:

    ##############################################################
    # 1. Instalar kubeadm, kubelet e kubectl
    ##############################################################
    - name: Instalar kubeadm, kubelet e kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    ##############################################################
    # 2. Habilitar kubelet
    ##############################################################
    - name: Habilitar kubelet
      systemd:
        name: kubelet
        enabled: yes

    ##############################################################
    # 3. Inicializar cluster Kubernetes
    ##############################################################
    - name: Inicializar cluster com kubeadm
      command: kubeadm init --pod-network-cidr=192.168.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    ##############################################################
    # 4. Criar diretório .kube
    ##############################################################
    - name: Criar diretório .kube
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755

    ##############################################################
    # 5. Copiar admin.conf para o usuário Ubuntu
    ##############################################################
    - name: Copiar admin.conf para o usuário ubuntu
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: 0644

    ##############################################################
    # 6. Aplicar rede Calico
    ##############################################################
    - name: Instalar rede Calico
      command: >
        kubectl apply
        --kubeconfig /etc/kubernetes/admin.conf
        -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml

    ##############################################################
    # 7. Mostrar comando de join
    ##############################################################
    - name: Exibir comando de join para os nodes workers
      command: kubeadm token create --print-join-command
      register: joincmd
      changed_when: false

    - debug:
        msg: "{{ joincmd.stdout }}"
